/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vsalinas.mavenproject1;

/**
 *
 * @author Vane_
 */
public class calculadora extends javax.swing.JFrame {
    
    String n1,n2,op;
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        this.setTitle("Calculadora");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numSiete = new javax.swing.JButton();
        numCuatro = new javax.swing.JButton();
        numUno = new javax.swing.JButton();
        numCero = new javax.swing.JButton();
        numOcho = new javax.swing.JButton();
        numCinco = new javax.swing.JButton();
        numDos = new javax.swing.JButton();
        opSigno = new javax.swing.JButton();
        numSeis = new javax.swing.JButton();
        numNueve = new javax.swing.JButton();
        numTres = new javax.swing.JButton();
        opIgual = new javax.swing.JButton();
        opDivision = new javax.swing.JButton();
        opMultiplicacion = new javax.swing.JButton();
        opSuma = new javax.swing.JButton();
        txtOperaciones = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        opResta = new javax.swing.JButton();
        opPunto = new javax.swing.JButton();
        opBorrar = new javax.swing.JButton();
        opReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numSiete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numSiete.setText("7");
        numSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSieteActionPerformed(evt);
            }
        });

        numCuatro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numCuatro.setText("4");
        numCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCuatroActionPerformed(evt);
            }
        });

        numUno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numUno.setText("1");
        numUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numUnoActionPerformed(evt);
            }
        });

        numCero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numCero.setText("0");
        numCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCeroActionPerformed(evt);
            }
        });

        numOcho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numOcho.setText("8");
        numOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOchoActionPerformed(evt);
            }
        });

        numCinco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numCinco.setText("5");
        numCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCincoActionPerformed(evt);
            }
        });

        numDos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numDos.setText("2");
        numDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDosActionPerformed(evt);
            }
        });

        opSigno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opSigno.setText("+/-");
        opSigno.setMaximumSize(new java.awt.Dimension(70, 70));
        opSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSignoActionPerformed(evt);
            }
        });

        numSeis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numSeis.setText("6");
        numSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSeisActionPerformed(evt);
            }
        });

        numNueve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numNueve.setText("9");
        numNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numNueveActionPerformed(evt);
            }
        });

        numTres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numTres.setText("3");
        numTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTresActionPerformed(evt);
            }
        });

        opIgual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opIgual.setText("=");
        opIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIgualActionPerformed(evt);
            }
        });

        opDivision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opDivision.setText("/");
        opDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDivisionActionPerformed(evt);
            }
        });

        opMultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opMultiplicacion.setText("*");
        opMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMultiplicacionActionPerformed(evt);
            }
        });

        opSuma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opSuma.setText("+");
        opSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSumaActionPerformed(evt);
            }
        });

        txtOperaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOperaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtResultado.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.setActionCommand("<Not Set>");
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        opResta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opResta.setText("-");
        opResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRestaActionPerformed(evt);
            }
        });

        opPunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opPunto.setText(".");
        opPunto.setMaximumSize(new java.awt.Dimension(70, 70));
        opPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPuntoActionPerformed(evt);
            }
        });

        opBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opBorrar.setText("<-");
        opBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opBorrarActionPerformed(evt);
            }
        });

        opReiniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opReiniciar.setText("CE");
        opReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultado)
                    .addComponent(txtOperaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numCero, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(numUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(opPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opSigno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(opDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addComponent(opMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(opResta, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(opReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(opBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(opIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numDos, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(opSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSieteActionPerformed
        txtResultado.setText(txtResultado.getText()+"7");
    }//GEN-LAST:event_numSieteActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        //if (){
            
        //}
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void opSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSignoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opSignoActionPerformed

    private void numOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOchoActionPerformed
        txtResultado.setText(txtResultado.getText()+"8");
    }//GEN-LAST:event_numOchoActionPerformed

    private void numNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numNueveActionPerformed
        txtResultado.setText(txtResultado.getText()+"9");
    }//GEN-LAST:event_numNueveActionPerformed

    private void numCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCuatroActionPerformed
        txtResultado.setText(txtResultado.getText()+"4");
    }//GEN-LAST:event_numCuatroActionPerformed

    private void numCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCincoActionPerformed
        txtResultado.setText(txtResultado.getText()+"5");
    }//GEN-LAST:event_numCincoActionPerformed

    private void numSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSeisActionPerformed
        txtResultado.setText(txtResultado.getText()+"6");
    }//GEN-LAST:event_numSeisActionPerformed

    private void numUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numUnoActionPerformed
        txtResultado.setText(txtResultado.getText()+"1");
    }//GEN-LAST:event_numUnoActionPerformed

    private void numDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDosActionPerformed
        txtResultado.setText(txtResultado.getText()+"2");
    }//GEN-LAST:event_numDosActionPerformed

    private void numTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTresActionPerformed
        txtResultado.setText(txtResultado.getText()+"3");
    }//GEN-LAST:event_numTresActionPerformed

    private void numCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCeroActionPerformed
        txtResultado.setText(txtResultado.getText()+"0");
    }//GEN-LAST:event_numCeroActionPerformed

    private void opPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPuntoActionPerformed
        String cad = txtResultado.getText();
        
        if(cad.length()<=0){
            txtResultado.setText("0.");
        }else if(!punto(txtResultado.getText())){
            txtResultado.setText(txtResultado.getText()+".");
        }
    }//GEN-LAST:event_opPuntoActionPerformed

    private void opBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opBorrarActionPerformed
        String cad = txtResultado.getText();
        
        if(cad.length()>0){
            cad = cad.substring(0, cad.length()-1);
            txtResultado.setText(cad);
        }
    }//GEN-LAST:event_opBorrarActionPerformed

    private void opReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opReiniciarActionPerformed
        txtResultado.setText("");
    }//GEN-LAST:event_opReiniciarActionPerformed

    private void opDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDivisionActionPerformed
        if(!txtResultado.getText().equals("")){
            n1=txtResultado.getText();
            op="/";
            txtResultado.setText("");
        }
    }//GEN-LAST:event_opDivisionActionPerformed

    private void opMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMultiplicacionActionPerformed
        if(!txtResultado.getText().equals("")){
            n1=txtResultado.getText();
            op="*";
            txtResultado.setText("");
        }
    }//GEN-LAST:event_opMultiplicacionActionPerformed

    private void opRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRestaActionPerformed
        if(!txtResultado.getText().equals("")){
            n1=txtResultado.getText();
            op="-";
            txtResultado.setText("");
        }
    }//GEN-LAST:event_opRestaActionPerformed

    private void opSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSumaActionPerformed
        //txtResultado.setText(txtResultado.getText()+"+");
        if(!txtResultado.getText().equals("")){
            n1=txtResultado.getText();
            op="+";
            txtResultado.setText("");
            //resultados.setText(n1+op);
        }
    }//GEN-LAST:event_opSumaActionPerformed

    private void opIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIgualActionPerformed
        n2=txtResultado.getText();
        
        if(!n2.equals("")){
            String resultado=operaciones(n1,op,n2);
            txtResultado.setText(resultado);
        }
    }//GEN-LAST:event_opIgualActionPerformed

    public static Boolean punto(String cad){
        boolean resultado = false;
        
        for (int i=0; i<cad.length(); i++){
            if (cad.substring(i, i+1).equals(".")){
                resultado = true;
                break;
            }
        }
        return resultado;
    }
    
    public static String operaciones(String n1,String op,String n2){
        double total=0.0;
                
        if(op.equals("/")){
            total=Double.parseDouble(n1)/Double.parseDouble(n2);
        }
        if(op.equals("*")){
            total=Double.parseDouble(n1)*Double.parseDouble(n2);
        }
        if(op.equals("-")){
            total=Double.parseDouble(n1)-Double.parseDouble(n2);
        }
        if(op.equals("+")){
            total=Double.parseDouble(n1)+Double.parseDouble(n2);
        }
        
        String resultado = Double.toString(total);
        return resultado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton numCero;
    private javax.swing.JButton numCinco;
    private javax.swing.JButton numCuatro;
    private javax.swing.JButton numDos;
    private javax.swing.JButton numNueve;
    private javax.swing.JButton numOcho;
    private javax.swing.JButton numSeis;
    private javax.swing.JButton numSiete;
    private javax.swing.JButton numTres;
    private javax.swing.JButton numUno;
    private javax.swing.JButton opBorrar;
    private javax.swing.JButton opDivision;
    private javax.swing.JButton opIgual;
    private javax.swing.JButton opMultiplicacion;
    private javax.swing.JButton opPunto;
    private javax.swing.JButton opReiniciar;
    private javax.swing.JButton opResta;
    private javax.swing.JButton opSigno;
    private javax.swing.JButton opSuma;
    private javax.swing.JLabel txtOperaciones;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
